-- =============================================================================
-- 03b_raw_to_atomic.sql - RAW to ATOMIC ETL Transformation
-- =============================================================================
-- One-time ETL to transform data from RAW (Bronze) to ATOMIC (Silver)
-- Executed after RAW data is populated by generate_synthetic_data.ipynb notebook
--
-- Transformation flow:
--   RAW.ENV_SENSOR_STREAM_STAGE      -> ATOMIC.ENVIRONMENTAL_READING
--   RAW.AGV_TELEMATICS_LOG_CDC       -> ATOMIC.EQUIPMENT_FAILURE (errors only)
--   RAW.EQUIPMENT_STATE_LOG_CDC      -> ATOMIC.EQUIPMENT_DOWNTIME
--   RAW.PROD_ORDER_HEADER_CDC        -> ATOMIC.WORK_ORDER
--   RAW.MATERIAL_DOCUMENT_CDC        -> ATOMIC.INVENTORY_TRANSACTION
--
-- Note: ATOMIC.ASSET and ATOMIC.PRODUCT are populated directly by the notebook
-- =============================================================================

-- =============================================================================
-- TRANSFORM ENV_SENSOR_STREAM_STAGE -> ENVIRONMENTAL_READING
-- =============================================================================
-- Note: ATOMIC.ASSET and ATOMIC.PRODUCT are populated directly by the 
-- generate_synthetic_data.ipynb notebook before this ETL runs

INSERT INTO ATOMIC.ENVIRONMENTAL_READING (
    READING_ID,
    SENSOR_ID,
    SENSOR_TYPE,
    SITE_ID,
    ZONE_ID,
    PRODUCTION_LINE_ID,
    READING_TIMESTAMP,
    METRIC_NAME,
    METRIC_VALUE,
    UNIT_OF_MEASURE,
    QUALITY_FLAG
)
SELECT 
    READING_ID,
    SENSOR_ID,
    SENSOR_TYPE,
    1 AS SITE_ID,  -- All readings from VoltStream Gigafactory
    ZONE_ID,
    PRODUCTION_LINE_ID,
    READING_TIMESTAMP,
    METRIC_NAME,
    METRIC_VALUE,
    UNIT_OF_MEASURE,
    QUALITY_FLAG
FROM RAW.ENV_SENSOR_STREAM_STAGE;

-- =============================================================================
-- TRANSFORM PROD_ORDER_HEADER_CDC -> WORK_ORDER
-- =============================================================================

INSERT INTO ATOMIC.WORK_ORDER (
    WORK_ORDER_ID,
    WORK_ORDER_NUMBER,
    WORK_ORDER_TYPE,
    PRODUCT_ID,
    SITE_ID,
    WORK_CENTER_ID,
    PRODUCTION_LINE_ID,
    PLANNED_QUANTITY,
    COMPLETED_QUANTITY,
    SCRAPPED_QUANTITY,
    WORK_ORDER_STATUS,
    PRIORITY,
    PLANNED_START_DATE,
    PLANNED_COMPLETION_DATE,
    ACTUAL_START_DATE,
    ACTUAL_COMPLETION_DATE,
    ACTUAL_START_TIMESTAMP,
    ACTUAL_END_TIMESTAMP,
    SHIFT_ID
)
SELECT 
    ROW_NUMBER() OVER (ORDER BY po.ORDER_ID) AS WORK_ORDER_ID,
    po.ORDER_ID AS WORK_ORDER_NUMBER,
    po.ORDER_TYPE AS WORK_ORDER_TYPE,
    p.PRODUCT_ID,
    1 AS SITE_ID,
    wc.WORK_CENTER_ID,
    po.PRODUCTION_LINE_ID,
    po.TARGET_QTY AS PLANNED_QUANTITY,
    po.ACTUAL_QTY AS COMPLETED_QUANTITY,  -- Use actual quantity produced (may be < TARGET_QTY)
    GREATEST(0, po.TARGET_QTY - COALESCE(po.ACTUAL_QTY, po.TARGET_QTY)) AS SCRAPPED_QUANTITY,  -- Difference treated as scrap/loss
    po.ORDER_STATUS AS WORK_ORDER_STATUS,
    po.PRIORITY::VARCHAR(50) AS PRIORITY,
    DATE(po.SCHED_START) AS PLANNED_START_DATE,
    DATE(po.SCHED_END) AS PLANNED_COMPLETION_DATE,
    DATE(po.ACTUAL_START) AS ACTUAL_START_DATE,
    DATE(po.ACTUAL_END) AS ACTUAL_COMPLETION_DATE,
    po.ACTUAL_START AS ACTUAL_START_TIMESTAMP,
    po.ACTUAL_END AS ACTUAL_END_TIMESTAMP,
    -- Derive SHIFT_ID from scheduled start time
    s.SHIFT_ID
FROM RAW.PROD_ORDER_HEADER_CDC po
LEFT JOIN ATOMIC.PRODUCT p ON po.SKU = p.PRODUCT_CODE AND p.IS_CURRENT_FLAG = TRUE
LEFT JOIN ATOMIC.WORK_CENTER wc ON wc.WORK_CENTER_CODE = 'WC_' || po.PRODUCTION_LINE_ID AND wc.IS_CURRENT_FLAG = TRUE
LEFT JOIN ATOMIC.SHIFT s ON 
    CASE 
        WHEN HOUR(po.SCHED_START) BETWEEN 6 AND 13 THEN 'SHIFT_1'
        WHEN HOUR(po.SCHED_START) BETWEEN 14 AND 21 THEN 'SHIFT_2'
        ELSE 'SHIFT_3'
    END = s.SHIFT_CODE AND s.IS_CURRENT_FLAG = TRUE;

-- =============================================================================
-- TRANSFORM EQUIPMENT_STATE_LOG_CDC -> EQUIPMENT_DOWNTIME
-- =============================================================================
-- Only insert records where STATE_CODE indicates downtime (2=IDLE, 3=FAULT, 4=SETUP)

INSERT INTO ATOMIC.EQUIPMENT_DOWNTIME (
    EQUIPMENT_DOWNTIME_ID,
    ASSET_ID,
    WORK_CENTER_ID,
    DOWNTIME_START_TIMESTAMP,
    DOWNTIME_END_TIMESTAMP,
    DOWNTIME_DURATION_HOURS,
    DOWNTIME_TYPE,
    DOWNTIME_REASON_CODE,
    SHIFT_ID,
    STATE_CODE,
    STATE_NAME,
    REASON_DESCRIPTION,
    OPERATOR_ID
)
SELECT 
    ROW_NUMBER() OVER (ORDER BY e.EVENT_TIMESTAMP) AS EQUIPMENT_DOWNTIME_ID,
    a.ASSET_ID,
    wc.WORK_CENTER_ID,
    e.EVENT_TIMESTAMP AS DOWNTIME_START_TIMESTAMP,
    DATEADD(second, e.DURATION_SECONDS, e.EVENT_TIMESTAMP) AS DOWNTIME_END_TIMESTAMP,
    e.DURATION_SECONDS / 3600.0 AS DOWNTIME_DURATION_HOURS,
    CASE 
        WHEN e.STATE_CODE IN (2, 4) THEN 'PLANNED'
        WHEN e.STATE_CODE = 3 THEN 'UNPLANNED'
        ELSE 'OTHER'
    END AS DOWNTIME_TYPE,
    e.REASON_CODE AS DOWNTIME_REASON_CODE,
    s.SHIFT_ID,
    e.STATE_CODE,
    e.STATE_NAME,
    e.REASON_DESCRIPTION,
    e.OPERATOR_ID
FROM RAW.EQUIPMENT_STATE_LOG_CDC e
LEFT JOIN ATOMIC.ASSET a ON e.ASSET_ID = a.ASSET_CODE AND a.IS_CURRENT_FLAG = TRUE
LEFT JOIN ATOMIC.WORK_CENTER wc ON wc.WORK_CENTER_CODE = 'WC_' || e.PRODUCTION_LINE_ID AND wc.IS_CURRENT_FLAG = TRUE
LEFT JOIN ATOMIC.SHIFT s ON e.SHIFT_ID = s.SHIFT_CODE AND s.IS_CURRENT_FLAG = TRUE
WHERE e.STATE_CODE IN (2, 3, 4);  -- IDLE, FAULT, SETUP only

-- =============================================================================
-- TRANSFORM AGV_TELEMATICS_LOG_CDC -> EQUIPMENT_FAILURE (errors only)
-- =============================================================================

INSERT INTO ATOMIC.EQUIPMENT_FAILURE (
    EQUIPMENT_FAILURE_ID,
    FAILURE_NUMBER,
    FAILURE_DATE,
    FAILURE_TIMESTAMP,
    ASSET_ID,
    FAILURE_MODE,
    FAILURE_DESCRIPTION,
    FAILURE_SYMPTOMS,
    FAILURE_CAUSE,
    FAILURE_SEVERITY,
    ERROR_CODE,
    ERROR_MESSAGE,
    ZONE_ID,
    ROUTE_SEGMENT
)
SELECT 
    ROW_NUMBER() OVER (ORDER BY t.EVENT_TIMESTAMP) AS EQUIPMENT_FAILURE_ID,
    t.MSG_ID AS FAILURE_NUMBER,
    DATE(t.EVENT_TIMESTAMP) AS FAILURE_DATE,
    t.EVENT_TIMESTAMP AS FAILURE_TIMESTAMP,
    a.ASSET_ID,
    CASE 
        WHEN t.ERROR_CODE LIKE 'AGV-ERR-99%' THEN 'SENSOR'
        WHEN t.ERROR_CODE LIKE 'AGV-ERR-01%' THEN 'ELECTRICAL'
        WHEN t.ERROR_CODE LIKE 'AGV-ERR-42%' THEN 'SENSOR'
        WHEN t.ERROR_CODE LIKE 'AGV-ERR-55%' THEN 'SOFTWARE'
        ELSE 'OTHER'
    END AS FAILURE_MODE,
    t.ERROR_MESSAGE AS FAILURE_DESCRIPTION,
    t.ERROR_MESSAGE AS FAILURE_SYMPTOMS,
    CASE 
        WHEN t.ERROR_CODE = 'AGV-ERR-99' THEN 'Dust accumulation on optical sensor'
        WHEN t.ERROR_CODE = 'AGV-ERR-01' THEN 'Low battery level'
        WHEN t.ERROR_CODE = 'AGV-ERR-42' THEN 'Physical obstruction in path'
        WHEN t.ERROR_CODE = 'AGV-ERR-55' THEN 'Network connectivity issue'
        ELSE 'Unknown cause'
    END AS FAILURE_CAUSE,
    t.ERROR_SEVERITY AS FAILURE_SEVERITY,
    t.ERROR_CODE,
    t.ERROR_MESSAGE,
    t.ZONE_ID,
    t.ROUTE_SEGMENT
FROM RAW.AGV_TELEMATICS_LOG_CDC t
LEFT JOIN ATOMIC.ASSET a ON t.AGV_ID = a.ASSET_CODE AND a.IS_CURRENT_FLAG = TRUE
WHERE t.ERROR_CODE IS NOT NULL;

-- =============================================================================
-- TRANSFORM MATERIAL_DOCUMENT_CDC -> INVENTORY_TRANSACTION
-- =============================================================================

INSERT INTO ATOMIC.INVENTORY_TRANSACTION (
    INVENTORY_TRANSACTION_ID,
    TRANSACTION_NUMBER,
    TRANSACTION_DATE,
    TRANSACTION_TYPE,
    PRODUCT_ID,
    SITE_ID,
    TRANSACTION_QUANTITY,
    TRANSACTION_REASON_CODE,
    SOURCE_DOCUMENT_TYPE,
    SOURCE_DOCUMENT_REFERENCE,
    BATCH_ID,
    STOCK_TYPE,
    STORAGE_LOCATION,
    MOVEMENT_TYPE
)
SELECT 
    ROW_NUMBER() OVER (ORDER BY m.POSTING_DATE, m.MAT_DOC_ID) AS INVENTORY_TRANSACTION_ID,
    m.MAT_DOC_ID AS TRANSACTION_NUMBER,
    m.POSTING_DATE::TIMESTAMP_NTZ AS TRANSACTION_DATE,
    CASE 
        WHEN m.MVMT_TYPE = '101' THEN 'GOODS_RECEIPT'
        WHEN m.MVMT_TYPE = '261' THEN 'GOODS_ISSUE'
        WHEN m.MVMT_TYPE = '321' THEN 'TRANSFER'
        WHEN m.MVMT_TYPE = '601' THEN 'SHIPMENT'
        ELSE 'OTHER'
    END AS TRANSACTION_TYPE,
    p.PRODUCT_ID,
    1 AS SITE_ID,
    m.QUANTITY AS TRANSACTION_QUANTITY,
    m.MVMT_TYPE AS TRANSACTION_REASON_CODE,
    'SAP_MATERIAL_DOC' AS SOURCE_DOCUMENT_TYPE,
    m.MAT_DOC_ID AS SOURCE_DOCUMENT_REFERENCE,
    m.BATCH_ID,
    m.STOCK_TYPE,
    m.STORAGE_LOCATION,
    m.MVMT_TYPE AS MOVEMENT_TYPE
FROM RAW.MATERIAL_DOCUMENT_CDC m
LEFT JOIN ATOMIC.PRODUCT p ON m.SKU = p.PRODUCT_CODE AND p.IS_CURRENT_FLAG = TRUE;

-- =============================================================================
-- VERIFICATION QUERIES
-- =============================================================================

SELECT 'ATOMIC.SITE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM ATOMIC.SITE
UNION ALL SELECT 'ATOMIC.WORK_CENTER', COUNT(*) FROM ATOMIC.WORK_CENTER
UNION ALL SELECT 'ATOMIC.SHIFT', COUNT(*) FROM ATOMIC.SHIFT
UNION ALL SELECT 'ATOMIC.ASSET', COUNT(*) FROM ATOMIC.ASSET
UNION ALL SELECT 'ATOMIC.PRODUCT', COUNT(*) FROM ATOMIC.PRODUCT
UNION ALL SELECT 'ATOMIC.WORK_ORDER', COUNT(*) FROM ATOMIC.WORK_ORDER
UNION ALL SELECT 'ATOMIC.EQUIPMENT_DOWNTIME', COUNT(*) FROM ATOMIC.EQUIPMENT_DOWNTIME
UNION ALL SELECT 'ATOMIC.EQUIPMENT_FAILURE', COUNT(*) FROM ATOMIC.EQUIPMENT_FAILURE
UNION ALL SELECT 'ATOMIC.INVENTORY_TRANSACTION', COUNT(*) FROM ATOMIC.INVENTORY_TRANSACTION
UNION ALL SELECT 'ATOMIC.ENVIRONMENTAL_READING', COUNT(*) FROM ATOMIC.ENVIRONMENTAL_READING
ORDER BY TABLE_NAME;

