-- =============================================================================
-- 04_ev_ope_schema.sql - EV_OPE Data Mart Layer (Dimensional Views)
-- =============================================================================
-- Consumer-facing dimensional views projecting from ATOMIC
-- Powers Cortex Analyst, Streamlit dashboards, and ML models
--
-- VIEWS (projected from ATOMIC):
--   DIM_ASSET, DIM_PRODUCT, DIM_SHIFT
--   OPE_DAILY_FACT, AGV_FAILURE_ANALYSIS
--   V_OPE_TRENDS, V_AGV_HEALTH, V_ACTIVE_ALERTS
--
-- TABLES (write targets for ML and Cortex):
--   PREDICTIVE_MAINTENANCE_ALERTS, DOCUMENT_CHUNKS
-- =============================================================================

USE SCHEMA EV_OPE;

-- =============================================================================
-- DIMENSION VIEWS
-- =============================================================================

-- DIM_ASSET - Asset dimension view (projects from ATOMIC.ASSET)
CREATE OR REPLACE VIEW DIM_ASSET AS
SELECT 
    ASSET_ID,
    ASSET_CODE,
    ASSET_NAME,
    ASSET_DESCRIPTION,
    ASSET_TYPE,
    ASSET_CLASS,
    ASSET_STATUS,
    PARENT_ASSET_ID,
    PRODUCTION_LINE_ID,
    ZONE_ID,
    MANUFACTURER,
    MODEL_NUMBER,
    SERIAL_NUMBER,
    ACQUISITION_DATE AS INSTALLATION_DATE,
    -- Mapping columns for compatibility
    ASSET_CODE AS MES_ASSET_ID,
    'WC_' || PRODUCTION_LINE_ID AS ERP_WORK_CENTER,
    'IOT_' || ASSET_CODE AS IOT_DEVICE_ID
FROM ATOMIC.ASSET
WHERE IS_CURRENT_FLAG = TRUE;

-- DIM_PRODUCT - Product dimension view (projects from ATOMIC.PRODUCT)
CREATE OR REPLACE VIEW DIM_PRODUCT AS
SELECT 
    PRODUCT_ID,
    PRODUCT_CODE AS SKU,
    PRODUCT_NAME,
    PRODUCT_DESCRIPTION_SHORT AS PRODUCT_DESCRIPTION,
    PRODUCT_CATEGORY,
    PRODUCT_FAMILY,
    PRODUCT_LINE,
    UNIT_OF_MEASURE,
    STANDARD_COST,
    STANDARD_CYCLE_TIME_SEC
FROM ATOMIC.PRODUCT
WHERE IS_CURRENT_FLAG = TRUE;

-- DIM_SHIFT - Shift dimension view (projects from ATOMIC.SHIFT)
CREATE OR REPLACE VIEW DIM_SHIFT AS
SELECT 
    SHIFT_CODE AS SHIFT_ID,
    SHIFT_NAME,
    START_TIME AS SHIFT_START_TIME,
    END_TIME AS SHIFT_END_TIME,
    SHIFT_DURATION_HOURS
FROM ATOMIC.SHIFT
WHERE IS_CURRENT_FLAG = TRUE;

-- =============================================================================
-- OPE_DAILY_FACT - Executive Dashboard Metrics (computed from ATOMIC)
-- =============================================================================
-- Aggregates work orders, downtime, failures, and environmental data by day/line/shift
-- Maintains same schema as original table for Streamlit compatibility

CREATE OR REPLACE VIEW OPE_DAILY_FACT AS
WITH work_order_metrics AS (
    -- Aggregate work orders by date, line, shift
    SELECT 
        wo.PLANNED_START_DATE AS METRIC_DATE,
        wo.PRODUCTION_LINE_ID,
        s.SHIFT_CODE AS SHIFT_ID,
        SUM(wo.PLANNED_QUANTITY) AS PLANNED_QUANTITY,
        SUM(COALESCE(wo.COMPLETED_QUANTITY, 0)) AS ACTUAL_QUANTITY,
        SUM(COALESCE(wo.SCRAPPED_QUANTITY, 0)) AS SCRAP_QUANTITY,
        COUNT(*) AS ORDER_COUNT
    FROM ATOMIC.WORK_ORDER wo
    LEFT JOIN ATOMIC.SHIFT s ON wo.SHIFT_ID = s.SHIFT_ID
    WHERE wo.IS_CURRENT_FLAG = TRUE
      AND wo.PRODUCTION_LINE_ID IS NOT NULL
    GROUP BY 1, 2, 3
),
downtime_metrics AS (
    -- Aggregate downtime by date, line, shift
    SELECT 
        DATE(ed.DOWNTIME_START_TIMESTAMP) AS METRIC_DATE,
        a.PRODUCTION_LINE_ID,
        s.SHIFT_CODE AS SHIFT_ID,
        SUM(ed.DOWNTIME_DURATION_HOURS * 60) AS DOWNTIME_MIN,
        SUM(CASE WHEN ed.DOWNTIME_REASON_CODE = 'STARVATION' THEN ed.DOWNTIME_DURATION_HOURS * 60 ELSE 0 END) AS STARVATION_DOWNTIME_MIN,
        SUM(CASE WHEN ed.DOWNTIME_REASON_CODE = 'BLOCKAGE' THEN ed.DOWNTIME_DURATION_HOURS * 60 ELSE 0 END) AS BLOCKAGE_DOWNTIME_MIN,
        SUM(CASE WHEN ed.DOWNTIME_REASON_CODE IN ('BREAKDOWN', 'FAULT') THEN ed.DOWNTIME_DURATION_HOURS * 60 ELSE 0 END) AS BREAKDOWN_DOWNTIME_MIN,
        SUM(CASE WHEN ed.DOWNTIME_REASON_CODE IN ('CHANGEOVER', 'SETUP') THEN ed.DOWNTIME_DURATION_HOURS * 60 ELSE 0 END) AS CHANGEOVER_MIN,
        COUNT(*) AS DOWNTIME_EVENT_COUNT
    FROM ATOMIC.EQUIPMENT_DOWNTIME ed
    LEFT JOIN ATOMIC.ASSET a ON ed.ASSET_ID = a.ASSET_ID
    LEFT JOIN ATOMIC.SHIFT s ON ed.SHIFT_ID = s.SHIFT_ID
    WHERE a.PRODUCTION_LINE_ID IS NOT NULL
    GROUP BY 1, 2, 3
),
agv_failure_metrics AS (
    -- Aggregate AGV failures by date, line (via zone mapping)
    SELECT 
        ef.FAILURE_DATE AS METRIC_DATE,
        -- Map zone to production line (simplified mapping)
        CASE 
            WHEN ef.ZONE_ID = 'ZONE_A' THEN 'LINE_1'
            WHEN ef.ZONE_ID = 'ZONE_B' THEN 'LINE_2'
            WHEN ef.ZONE_ID = 'ZONE_C' THEN 'LINE_3'
            WHEN ef.ZONE_ID = 'ZONE_D' THEN 'LINE_4'
            ELSE 'LINE_5'
        END AS PRODUCTION_LINE_ID,
        s.SHIFT_CODE AS SHIFT_ID,
        COUNT(*) AS AGV_FAILURE_COUNT,
        SUM(CASE WHEN ef.ERROR_CODE = 'AGV-ERR-99' THEN 1 ELSE 0 END) AS AGV_ERR_99_COUNT
    FROM ATOMIC.EQUIPMENT_FAILURE ef
    LEFT JOIN ATOMIC.ASSET a ON ef.ASSET_ID = a.ASSET_ID
    LEFT JOIN ATOMIC.SHIFT s ON 
        CASE 
            WHEN HOUR(ef.FAILURE_TIMESTAMP) BETWEEN 6 AND 13 THEN 'SHIFT_1'
            WHEN HOUR(ef.FAILURE_TIMESTAMP) BETWEEN 14 AND 21 THEN 'SHIFT_2'
            ELSE 'SHIFT_3'
        END = s.SHIFT_CODE
    WHERE a.ASSET_TYPE = 'AGV'
    GROUP BY 1, 2, 3
),
env_metrics AS (
    -- Aggregate environmental readings by date, line, shift
    SELECT 
        DATE(er.READING_TIMESTAMP) AS METRIC_DATE,
        er.PRODUCTION_LINE_ID,
        CASE 
            WHEN HOUR(er.READING_TIMESTAMP) BETWEEN 6 AND 13 THEN 'SHIFT_1'
            WHEN HOUR(er.READING_TIMESTAMP) BETWEEN 14 AND 21 THEN 'SHIFT_2'
            ELSE 'SHIFT_3'
        END AS SHIFT_ID,
        AVG(CASE WHEN er.SENSOR_TYPE = 'HUMIDITY' THEN er.METRIC_VALUE END) AS AVG_HUMIDITY,
        AVG(CASE WHEN er.SENSOR_TYPE = 'PM25' THEN er.METRIC_VALUE END) AS AVG_DUST_PM25,
        AVG(CASE WHEN er.SENSOR_TYPE = 'TEMPERATURE' THEN er.METRIC_VALUE END) AS AVG_TEMPERATURE
    FROM ATOMIC.ENVIRONMENTAL_READING er
    GROUP BY 1, 2, 3
)
SELECT 
    COALESCE(wo.METRIC_DATE, dt.METRIC_DATE, agv.METRIC_DATE, env.METRIC_DATE) AS METRIC_DATE,
    COALESCE(wo.PRODUCTION_LINE_ID, dt.PRODUCTION_LINE_ID, agv.PRODUCTION_LINE_ID, env.PRODUCTION_LINE_ID) AS PRODUCTION_LINE_ID,
    COALESCE(wo.SHIFT_ID, dt.SHIFT_ID, agv.SHIFT_ID, env.SHIFT_ID) AS SHIFT_ID,
    
    -- OEE Components (calculated from downtime)
    ROUND(100.0 - COALESCE(dt.DOWNTIME_MIN, 0) / 4.8, 2) AS OEE_AVAILABILITY_PCT,  -- 480 min shift
    ROUND(COALESCE(wo.ACTUAL_QUANTITY, 0) / NULLIF(COALESCE(wo.PLANNED_QUANTITY, 1), 0) * 100, 2) AS OEE_PERFORMANCE_PCT,
    ROUND((COALESCE(wo.ACTUAL_QUANTITY, 0) - COALESCE(wo.SCRAP_QUANTITY, 0)) / NULLIF(COALESCE(wo.ACTUAL_QUANTITY, 1), 0) * 100, 2) AS OEE_QUALITY_PCT,
    ROUND((100.0 - COALESCE(dt.DOWNTIME_MIN, 0) / 4.8) * 
          (COALESCE(wo.ACTUAL_QUANTITY, 0) / NULLIF(COALESCE(wo.PLANNED_QUANTITY, 1), 0)) * 
          ((COALESCE(wo.ACTUAL_QUANTITY, 0) - COALESCE(wo.SCRAP_QUANTITY, 0)) / NULLIF(COALESCE(wo.ACTUAL_QUANTITY, 1), 0)), 2) AS OEE_PCT,
    
    -- OPE Components (includes material flow efficiency)
    ROUND(100.0 - COALESCE(dt.STARVATION_DOWNTIME_MIN, 0) / 4.8, 2) AS OPE_VALUE_ADDED_TIME_PCT,
    ROUND(100.0 - COALESCE(agv.AGV_FAILURE_COUNT, 0) * 2, 2) AS OPE_MATERIAL_EFFICIENCY_PCT,  -- Each failure costs ~2% efficiency
    ROUND(COALESCE(wo.ACTUAL_QUANTITY, 0) / NULLIF(COALESCE(wo.PLANNED_QUANTITY, 1), 0) * 100, 2) AS OPE_FLOW_EFFICIENCY_PCT,
    -- OPE is OEE adjusted for starvation
    ROUND(GREATEST(0, 
        (100.0 - COALESCE(dt.DOWNTIME_MIN, 0) / 4.8) * 
        (COALESCE(wo.ACTUAL_QUANTITY, 0) / NULLIF(COALESCE(wo.PLANNED_QUANTITY, 1), 0)) * 
        ((COALESCE(wo.ACTUAL_QUANTITY, 0) - COALESCE(wo.SCRAP_QUANTITY, 0)) / NULLIF(COALESCE(wo.ACTUAL_QUANTITY, 1), 0)) *
        (1 - COALESCE(dt.STARVATION_DOWNTIME_MIN, 0) / 480)
    ), 2) AS OPE_PCT,
    
    -- Production Metrics
    COALESCE(wo.PLANNED_QUANTITY, 0) AS PLANNED_QUANTITY,
    COALESCE(wo.ACTUAL_QUANTITY, 0) AS ACTUAL_QUANTITY,
    COALESCE(wo.SCRAP_QUANTITY, 0) AS SCRAP_QUANTITY,
    ROUND((COALESCE(wo.ACTUAL_QUANTITY, 0) - COALESCE(wo.SCRAP_QUANTITY, 0)) / NULLIF(COALESCE(wo.ACTUAL_QUANTITY, 1), 0) * 100, 2) AS YIELD_PCT,
    
    -- Time Metrics (minutes)
    480 AS PLANNED_PRODUCTION_TIME_MIN,  -- 8-hour shift
    480 - COALESCE(dt.DOWNTIME_MIN, 0)::INTEGER AS ACTUAL_PRODUCTION_TIME_MIN,
    COALESCE(dt.DOWNTIME_MIN, 0)::INTEGER AS DOWNTIME_MIN,
    COALESCE(dt.STARVATION_DOWNTIME_MIN, 0)::INTEGER AS STARVATION_DOWNTIME_MIN,
    COALESCE(dt.BLOCKAGE_DOWNTIME_MIN, 0)::INTEGER AS BLOCKAGE_DOWNTIME_MIN,
    COALESCE(dt.BREAKDOWN_DOWNTIME_MIN, 0)::INTEGER AS BREAKDOWN_DOWNTIME_MIN,
    COALESCE(dt.CHANGEOVER_MIN, 0)::INTEGER AS CHANGEOVER_MIN,
    
    -- Cycle Time Metrics
    ROUND(480.0 * 60 / NULLIF(COALESCE(wo.ACTUAL_QUANTITY, 1), 0), 2) AS AVG_CYCLE_TIME_SEC,
    45.0 AS THEORETICAL_CYCLE_TIME_SEC,
    
    -- Environmental Context
    ROUND(COALESCE(env.AVG_HUMIDITY, 45), 2) AS AVG_HUMIDITY,
    ROUND(COALESCE(env.AVG_DUST_PM25, 10), 3) AS AVG_DUST_PM25,
    ROUND(COALESCE(env.AVG_TEMPERATURE, 22), 2) AS AVG_TEMPERATURE,
    
    -- AGV Performance Context
    COALESCE(agv.AGV_FAILURE_COUNT, 0) AS AGV_FAILURE_COUNT,
    COALESCE(agv.AGV_ERR_99_COUNT, 0) AS AGV_ERR_99_COUNT,
    
    -- Refresh metadata
    CURRENT_TIMESTAMP() AS _REFRESHED_TIMESTAMP
FROM work_order_metrics wo
FULL OUTER JOIN downtime_metrics dt 
    ON wo.METRIC_DATE = dt.METRIC_DATE 
    AND wo.PRODUCTION_LINE_ID = dt.PRODUCTION_LINE_ID 
    AND wo.SHIFT_ID = dt.SHIFT_ID
FULL OUTER JOIN agv_failure_metrics agv 
    ON COALESCE(wo.METRIC_DATE, dt.METRIC_DATE) = agv.METRIC_DATE 
    AND COALESCE(wo.PRODUCTION_LINE_ID, dt.PRODUCTION_LINE_ID) = agv.PRODUCTION_LINE_ID
    AND COALESCE(wo.SHIFT_ID, dt.SHIFT_ID) = agv.SHIFT_ID
FULL OUTER JOIN env_metrics env 
    ON COALESCE(wo.METRIC_DATE, dt.METRIC_DATE, agv.METRIC_DATE) = env.METRIC_DATE 
    AND COALESCE(wo.PRODUCTION_LINE_ID, dt.PRODUCTION_LINE_ID, agv.PRODUCTION_LINE_ID) = env.PRODUCTION_LINE_ID
    AND COALESCE(wo.SHIFT_ID, dt.SHIFT_ID, agv.SHIFT_ID) = env.SHIFT_ID
WHERE COALESCE(wo.METRIC_DATE, dt.METRIC_DATE, agv.METRIC_DATE, env.METRIC_DATE) IS NOT NULL;

-- =============================================================================
-- AGV_FAILURE_ANALYSIS - ML Training Data (computed from ATOMIC)
-- =============================================================================
-- Hourly AGV failure analysis showing correlation: Low Humidity → High Dust → AGV Failures

CREATE OR REPLACE VIEW AGV_FAILURE_ANALYSIS AS
WITH hourly_env AS (
    -- Aggregate environmental readings by hour and zone
    SELECT 
        DATE(er.READING_TIMESTAMP) AS ANALYSIS_DATE,
        HOUR(er.READING_TIMESTAMP) AS ANALYSIS_HOUR,
        er.ZONE_ID,
        AVG(CASE WHEN er.SENSOR_TYPE = 'HUMIDITY' THEN er.METRIC_VALUE END) AS AVG_HUMIDITY,
        MIN(CASE WHEN er.SENSOR_TYPE = 'HUMIDITY' THEN er.METRIC_VALUE END) AS MIN_HUMIDITY,
        MAX(CASE WHEN er.SENSOR_TYPE = 'HUMIDITY' THEN er.METRIC_VALUE END) AS MAX_HUMIDITY,
        AVG(CASE WHEN er.SENSOR_TYPE = 'PM25' THEN er.METRIC_VALUE END) AS AVG_DUST_PM25,
        MAX(CASE WHEN er.SENSOR_TYPE = 'PM25' THEN er.METRIC_VALUE END) AS MAX_DUST_PM25,
        AVG(CASE WHEN er.SENSOR_TYPE = 'TEMPERATURE' THEN er.METRIC_VALUE END) AS AVG_TEMPERATURE
    FROM ATOMIC.ENVIRONMENTAL_READING er
    GROUP BY 1, 2, 3
),
hourly_failures AS (
    -- Aggregate AGV failures by hour and zone
    SELECT 
        ef.FAILURE_DATE AS ANALYSIS_DATE,
        HOUR(ef.FAILURE_TIMESTAMP) AS ANALYSIS_HOUR,
        ef.ZONE_ID,
        COUNT(*) AS TOTAL_ERRORS,
        SUM(CASE WHEN ef.ERROR_CODE = 'AGV-ERR-99' THEN 1 ELSE 0 END) AS AGV_ERR_99_COUNT,
        SUM(CASE WHEN ef.ERROR_CODE = 'AGV-ERR-01' THEN 1 ELSE 0 END) AS AGV_ERR_01_COUNT,
        SUM(CASE WHEN ef.ERROR_CODE = 'AGV-ERR-42' THEN 1 ELSE 0 END) AS AGV_ERR_42_COUNT,
        SUM(CASE WHEN ef.ERROR_CODE = 'AGV-ERR-55' THEN 1 ELSE 0 END) AS AGV_ERR_55_COUNT
    FROM ATOMIC.EQUIPMENT_FAILURE ef
    LEFT JOIN ATOMIC.ASSET a ON ef.ASSET_ID = a.ASSET_ID
    WHERE a.ASSET_TYPE = 'AGV'
    GROUP BY 1, 2, 3
)
SELECT 
    env.ANALYSIS_DATE,
    env.ANALYSIS_HOUR,
    CASE 
        WHEN env.ANALYSIS_HOUR BETWEEN 6 AND 13 THEN 'SHIFT_1'
        WHEN env.ANALYSIS_HOUR BETWEEN 14 AND 21 THEN 'SHIFT_2'
        ELSE 'SHIFT_3'
    END AS SHIFT_ID,
    env.ZONE_ID,
    
    -- Environmental Features
    ROUND(COALESCE(env.AVG_HUMIDITY, 45), 3) AS AVG_HUMIDITY,
    ROUND(COALESCE(env.MIN_HUMIDITY, 40), 3) AS MIN_HUMIDITY,
    ROUND(COALESCE(env.MAX_HUMIDITY, 50), 3) AS MAX_HUMIDITY,
    ROUND(COALESCE(env.AVG_DUST_PM25, 10), 3) AS AVG_DUST_PM25,
    ROUND(COALESCE(env.MAX_DUST_PM25, 15), 3) AS MAX_DUST_PM25,
    ROUND(COALESCE(env.AVG_TEMPERATURE, 22), 3) AS AVG_TEMPERATURE,
    
    -- Humidity Categories
    CASE 
        WHEN COALESCE(env.AVG_HUMIDITY, 45) < 35 THEN 'LOW'
        WHEN COALESCE(env.AVG_HUMIDITY, 45) > 55 THEN 'HIGH'
        ELSE 'NORMAL'
    END AS HUMIDITY_CATEGORY,
    
    -- Dust Categories
    CASE 
        WHEN COALESCE(env.AVG_DUST_PM25, 10) > 25 THEN 'HIGH'
        WHEN COALESCE(env.AVG_DUST_PM25, 10) > 15 THEN 'MODERATE'
        ELSE 'LOW'
    END AS DUST_CATEGORY,
    
    -- AGV Operations (estimated - in production would come from actual operations table)
    100 AS TOTAL_AGV_OPERATIONS,
    100 - COALESCE(f.TOTAL_ERRORS, 0) AS SUCCESSFUL_OPERATIONS,
    COALESCE(f.TOTAL_ERRORS, 0) AS FAILED_OPERATIONS,
    ROUND(COALESCE(f.TOTAL_ERRORS, 0) / 100.0, 6) AS FAILURE_RATE,
    
    -- Error Breakdown
    COALESCE(f.TOTAL_ERRORS, 0) AS TOTAL_ERRORS,
    COALESCE(f.AGV_ERR_99_COUNT, 0) AS AGV_ERR_99_COUNT,
    COALESCE(f.AGV_ERR_01_COUNT, 0) AS AGV_ERR_01_COUNT,
    COALESCE(f.AGV_ERR_42_COUNT, 0) AS AGV_ERR_42_COUNT,
    COALESCE(f.AGV_ERR_55_COUNT, 0) AS AGV_ERR_55_COUNT,
    GREATEST(0, COALESCE(f.TOTAL_ERRORS, 0) - COALESCE(f.AGV_ERR_99_COUNT, 0) - COALESCE(f.AGV_ERR_01_COUNT, 0) - COALESCE(f.AGV_ERR_42_COUNT, 0) - COALESCE(f.AGV_ERR_55_COUNT, 0)) AS OTHER_ERROR_COUNT,
    
    -- ML Target Variables
    COALESCE(f.TOTAL_ERRORS, 0) / 100.0 > 0.05 AS IS_HIGH_FAILURE_PERIOD,
    ROUND(COALESCE(f.TOTAL_ERRORS, 0) / 100.0, 6) AS FAILURE_PROBABILITY,
    
    -- Downstream Impact (each ERR-99 causes starvation)
    COALESCE(f.AGV_ERR_99_COUNT, 0) AS STARVATION_EVENTS_CAUSED,
    COALESCE(f.AGV_ERR_99_COUNT, 0) * 15 AS STARVATION_DURATION_MIN  -- ~15 min per event
FROM hourly_env env
LEFT JOIN hourly_failures f 
    ON env.ANALYSIS_DATE = f.ANALYSIS_DATE 
    AND env.ANALYSIS_HOUR = f.ANALYSIS_HOUR 
    AND env.ZONE_ID = f.ZONE_ID;

-- =============================================================================
-- ANALYTICAL VIEWS FOR CORTEX ANALYST
-- =============================================================================

-- View optimized for OPE trend analysis
CREATE OR REPLACE VIEW V_OPE_TRENDS AS
SELECT
    METRIC_DATE,
    PRODUCTION_LINE_ID,
    SHIFT_ID,
    OEE_PCT,
    OPE_PCT,
    OEE_PCT - OPE_PCT AS OEE_OPE_GAP,
    STARVATION_DOWNTIME_MIN,
    AGV_FAILURE_COUNT,
    AGV_ERR_99_COUNT,
    AVG_HUMIDITY,
    AVG_DUST_PM25,
    ACTUAL_QUANTITY,
    YIELD_PCT,
    -- Rolling averages
    AVG(OPE_PCT) OVER (
        PARTITION BY PRODUCTION_LINE_ID 
        ORDER BY METRIC_DATE 
        ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
    ) AS OPE_7DAY_AVG,
    AVG(OPE_PCT) OVER (
        PARTITION BY PRODUCTION_LINE_ID 
        ORDER BY METRIC_DATE 
        ROWS BETWEEN 29 PRECEDING AND CURRENT ROW
    ) AS OPE_30DAY_AVG
FROM OPE_DAILY_FACT;

-- View for AGV health monitoring
CREATE OR REPLACE VIEW V_AGV_HEALTH AS
SELECT
    ANALYSIS_DATE,
    ANALYSIS_HOUR,
    ZONE_ID,
    AVG_HUMIDITY,
    AVG_DUST_PM25,
    HUMIDITY_CATEGORY,
    DUST_CATEGORY,
    TOTAL_AGV_OPERATIONS,
    FAILURE_RATE,
    AGV_ERR_99_COUNT,
    IS_HIGH_FAILURE_PERIOD,
    STARVATION_EVENTS_CAUSED,
    -- Risk score based on environmental conditions
    CASE 
        WHEN AVG_HUMIDITY < 30 AND AVG_DUST_PM25 > 30 THEN 'CRITICAL'
        WHEN AVG_HUMIDITY < 35 AND AVG_DUST_PM25 > 25 THEN 'HIGH'
        WHEN AVG_HUMIDITY < 40 AND AVG_DUST_PM25 > 20 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS ENVIRONMENTAL_RISK_LEVEL
FROM AGV_FAILURE_ANALYSIS;

-- =============================================================================
-- TABLES FOR ML MODEL OUTPUT AND CORTEX SEARCH
-- =============================================================================

-- PREDICTIVE_MAINTENANCE_ALERTS - ML model output (write target)
CREATE OR REPLACE TABLE PREDICTIVE_MAINTENANCE_ALERTS (
    -- Keys
    ALERT_ID NUMBER(38,0) AUTOINCREMENT,
    PREDICTION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    
    -- Prediction Target
    TARGET_ZONE_ID VARCHAR(20),
    TARGET_DATE DATE,
    TARGET_HOUR NUMBER(2),
    TARGET_SHIFT_ID VARCHAR(20),
    
    -- Environmental Forecast
    FORECAST_HUMIDITY NUMBER(8,3),
    FORECAST_DUST_PM25 NUMBER(8,3),
    
    -- Prediction Output
    FAILURE_PROBABILITY NUMBER(8,6),
    FAILURE_PROBABILITY_CATEGORY VARCHAR(20),
    PREDICTED_FAILURE_COUNT NUMBER(10),
    CONFIDENCE_SCORE NUMBER(8,6),
    
    -- Root Cause Analysis
    PRIMARY_RISK_FACTOR VARCHAR(50),
    CONTRIBUTING_FACTORS VARCHAR(500),
    
    -- Recommended Action
    RECOMMENDED_ACTION VARCHAR(100),
    ACTION_PRIORITY VARCHAR(20),
    ESTIMATED_PREVENTION_VALUE NUMBER(18,2),
    
    -- Action Status
    ACTION_STATUS VARCHAR(20) DEFAULT 'PENDING',
    ACTION_TAKEN_BY VARCHAR(100),
    ACTION_TAKEN_TIMESTAMP TIMESTAMP_NTZ,
    ACTION_NOTES VARCHAR(1000),
    
    -- Model Metadata
    MODEL_VERSION VARCHAR(50),
    MODEL_NAME VARCHAR(100),
    
    PRIMARY KEY (ALERT_ID)
)
COMMENT = 'Predictive maintenance alerts from ML model - drives Cortex Agent recommendations';

-- View for active alerts
CREATE OR REPLACE VIEW V_ACTIVE_ALERTS AS
SELECT
    ALERT_ID,
    PREDICTION_TIMESTAMP,
    TARGET_ZONE_ID,
    TARGET_DATE,
    TARGET_HOUR,
    TARGET_SHIFT_ID,
    FAILURE_PROBABILITY,
    FAILURE_PROBABILITY_CATEGORY,
    PRIMARY_RISK_FACTOR,
    RECOMMENDED_ACTION,
    ACTION_PRIORITY,
    ACTION_STATUS,
    ESTIMATED_PREVENTION_VALUE
FROM PREDICTIVE_MAINTENANCE_ALERTS
WHERE ACTION_STATUS IN ('PENDING', 'APPROVED', 'IN_PROGRESS')
  AND TARGET_DATE >= CURRENT_DATE();

-- DOCUMENT_CHUNKS - For Cortex Search
CREATE OR REPLACE TABLE DOCUMENT_CHUNKS (
    CHUNK_ID NUMBER(38,0) AUTOINCREMENT,
    DOCUMENT_NAME VARCHAR(500),
    DOCUMENT_TYPE VARCHAR(50),
    EQUIPMENT_MODEL VARCHAR(100),
    ERROR_CODE_TAG VARCHAR(20),
    
    -- Chunk content
    CHUNK_TEXT VARCHAR(16000),
    CHUNK_INDEX NUMBER(5),
    TOTAL_CHUNKS NUMBER(5),
    
    -- Metadata
    LANGUAGE VARCHAR(20) DEFAULT 'English',
    FILE_URL VARCHAR(1000),
    
    -- Audit
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    
    PRIMARY KEY (CHUNK_ID)
)
COMMENT = 'Chunked document text for Cortex Search - maintenance manuals and SOPs';

-- Enable change tracking for Cortex Search
ALTER TABLE DOCUMENT_CHUNKS SET CHANGE_TRACKING = TRUE;
